library(MASS)
str(cement)
cor(cement)
cor(cement$x1,cement$x3,use = "everything",method=c("pearson"))
cov(x=Cars93$Weight,y=Cars93$Horsepower,use = "everything",method=c("pearson"))
plot(Horsepower ~ Weight,data=Cars93,xlab="Weight",ylab="Horsepower")
abline(lm(Horsepower ~ Weight,data = Cars93),col="blue")
cor.test(Cars93$Weight,Cars93$Horsepower)
x<-c(1,2,3,4,5,6,7,8,9,10,11,12,13)
t.test(x,alternative = c("greater"),mu=3,conf.level = 0.95)
cor(Cars93$Price,Cars93$RPM,use = "everything",method=c("pearson"))
cov(x=Cars93$Price,y=Cars93$RPM,use = "everything",method=c("pearson"))
plot(Cars93$Price ~ RPM,data=Cars93,xlab="Price",ylab="RPM")
abline(lm(Price ~ RPM,data = Cars93),col="blue")
t.test(Cars93$Price,alternative = c("less"),mu=19200,conf.level = 0.95)
